In [2]:
import pandas as pd
import numpy as np
data = pd.read_csv('./files_for_lab/csv_files/marketing_customer_analysis.csv')

In [13]:
pd.read_csv('./files_for_lab/csv_files/marketing_customer_analysis.csv').describe().T

,count,mean,std,min,25%,50%,75%,max
Customer Lifetime Value,9134.0,8004.940475,6870.967608,1898.007675,3994.251794,5780.182197,8962.167041,83325.381190
Income,9134.0,37657.380009,30379.904734,0.000000,0.000000,33889.500000,62320.000000,99981.000000
Monthly Premium Auto,9134.0,93.219291,34.407967,61.000000,68.000000,83.000000,109.000000,298.000000
Months Since Last Claim,9134.0,15.097000,10.073257,0.000000,6.000000,14.000000,23.000000,35.000000
Months Since Policy Inception,9134.0,48.064594,27.905991,0.000000,24.000000,48.000000,71.000000,99.000000
Number of Open Complaints,9134.0,0.384388,0.910384,0.000000,0.000000,0.000000,0.000000,5.000000
Number of Policies,9134.0,2.966170,2.390182,1.000000,1.000000,2.000000,4.000000,9.000000
Total Claim Amount,9134.0,434.088794,290.500092,0.099007,272.258244,383.945434,547.514839,2893.239678

In [11]:
data = pd.read_csv('./files_for_lab/csv_files/marketing_customer_analysis.csv')
Total = data.groupby['./files_for_lab/csv_files/marketing_customer_analysis.csv'].sum()

print (Total)

TypeError: 'method' object is not subscriptable